version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  tickly-back:
    build:
      context: ./backend  # Chemin vers le Dockerfile du backend
      dockerfile: Dockerfile  # Assure-toi que ton Dockerfile est nommé correctement
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      default:
        aliases:
          - tickly-back

  tickly-frontend:
    build:
      context: ./frontend  # Chemin vers ton Dockerfile Angular
      dockerfile: Dockerfile.prod  # Assure-toi que ton Dockerfile est nommé correctement
    restart: unless-stopped
    ports:
      - '8080:80'  # Mappe le port 80 du conteneur sur le port 8080 de l'hôte
    networks:
      default:
        aliases:
          - tickly-frontend

volumes:
  postgres:
