name: CI/CD for Full Stack

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushes à la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupérer le code source depuis le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Se connecter à Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Étape 3: Construire l'image Docker pour le frontend
      - name: Build Docker image for frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tickly-frontend:latest -f frontend/Dockerfile.prod ./frontend

      # Étape 4: Construire l'image Docker pour le backend
      - name: Build Docker image for backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tickly-back:latest -f ./backend/Dockerfile .

      # Étape 5: Pousser les images Docker sur Docker Hub
      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tickly-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tickly-back:latest

      # Étape 6: Installer sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Étape 7: Déployer sur le VPS
      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            # Naviguer vers le répertoire de l'application sur le VPS
            cd /root/tickly

            # Arrêter et supprimer les conteneurs existants
            docker-compose -f docker-compose.prod.yml down

            # Télécharger les nouvelles images
            docker-compose -f docker-compose.prod.yml pull

            # Démarrer les nouveaux conteneurs
            docker-compose -f docker-compose.prod.yml up -d
          EOF

      # Étape 8: Vérifier l'état des conteneurs sur le VPS
      - name: Check Docker container status
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "docker ps"
